# NumPy Arrays

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
myarr = np.array(mylist)

In [5]:
type(myarr)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
len(np.linspace(0,5,21))

21

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(2)

array([0.15125738, 0.55251857])

In [18]:
np.random.rand(5,2)

array([[0.55825175, 0.21783757],
       [0.3241929 , 0.0014196 ],
       [0.06155903, 0.51055242],
       [0.24653938, 0.23517243],
       [0.96223467, 0.22333834]])

In [19]:
np.random.randn(2)

array([-2.49218925, -0.7837913 ])

In [20]:
np.random.randn(2,3)

array([[-0.02389919,  1.42422982, -0.7669919 ],
       [ 1.8971459 ,  1.08805358, -0.61206883]])

In [21]:
np.random.randint(1,100)

1

In [22]:
np.random.randint(1,6,(4,5))

array([[2, 2, 5, 2, 2],
       [5, 2, 4, 2, 4],
       [1, 4, 3, 2, 1],
       [3, 5, 2, 1, 5]])

In [23]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [24]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [25]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [26]:
arr = np.arange(0,25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr = np.random.randint(0,101,10)

In [30]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [31]:
ranarr.max()

np.int64(99)

In [32]:
ranarr.min()

np.int64(2)

In [33]:
ranarr.argmax()

np.int64(5)

In [34]:
ranarr.argmin()

np.int64(7)

In [35]:
ranarr.dtype

dtype('int64')

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr.shape

(5, 5)

In [41]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])